spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          #配置RSA的公钥访问地址
          jwk-set-uri: 'http://127.0.0.1:9002/rsa/publicKey'
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
  cloud:
    # 路由网关配置
    gateway:
      # 设置与服务注册发现组件结合，这样可以采用服务名的路由策略
      discovery:
        locator:
          # 启用自动根据服务ID生成路由
          enabled: true
          # 设置路由的路径为小写的服务ID
          lower-case-service-id: true
      # 配置路由规则
      routes:
        # 采用自定义路由 ID（有固定用法，不同的 id 有不同的功能
        - id: maps-auth
          # 采用 LoadBalanceClient 方式请求，以 lb:// 开头，后面的是注册在 Nacos 上的服务名
          uri: lb://maps-auth
          # Predicate 翻译过来是“谓词”的意思，必须，主要作用是匹配用户的请求，有很多种用法
          predicates:
            # Method 方法谓词，这里是匹配 GET 和 POST 请求
            - Method=GET,POST
            - Path=/auth/**
          filters:
            - StripPrefix=1 # 移除前缀 auth
        - id: maps-ims
          uri: lb://maps-ims
          predicates:
            - Method=GET,POST
            - Path=/ivt/**
        - id: maps-doc
          uri: lb://maps-doc
          predicates:
            - Path=/doc/doc.html,/doc/**,/static/**
          filters:
            - StripPrefix=1
        - id: maps-actuator
          uri: lb://maps-actuator
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: "*"

# 配置日志级别，方别调试
logging:
  level:
    org.springframework.cloud.gateway: debug

# 配置feign
feign:
  client:
    config:
      #这里填具体的服务名称（也可以填default，表示对所有服务生效）
      default:
        #connectTimeout和readTimeout这两个得一起配置才会生效
        connectTimeout: 5000
        readTimeout: 5000
  okhttp:
    enabled: true

# 配置白名单路径
whitelist:
  urls:
    - "/auth/oauth/**"
#    - "/doc/**"